### ISSUE TITLE
Question: Iceologer's face animation error!

### ISSUE THREAD

**Issue by Puzzle86cn** [SebSemos/F.M.R.P-Freshly-Modded-#11]
1. The eyes of Iceologer(friends and Foes) are white.
 2 There is no animation of Ravage (Ravage & Cabbage).
 My game version is 1.20.1 & Forge - 47.3.11! 
 
![af5600ef2325e2ea8ee7c963b6bcaafa](https://github.com/user-attachments/assets/dc2d788b-394f-4bf3-8f2f-602881dddd35)
![8105fd267824d25a6c78342052b29203](https://github.com/user-attachments/assets/01157adb-161f-478a-8ff1-9e10c116242d)
![cf4b087b4a10a2a6477b1ebc062975bb](https://github.com/user-attachments/assets/a4c37dc3-dab4-4323-bef4-81756d4420f2)
![459f161b8ca5f11614868b6d4c0b550e](https://github.com/user-attachments/assets/9933bd9d-802f-4a70-ae2e-a416c6fbdee0)
Thank you.

**Comment by SebSemos** [comment]
Iceologer is fix with 1.5.9
https://modrinth.com/resourcepack/freshly-modded/version/1.5.9

I check on the ravager a little bit later

**Comment by SebSemos** [comment]
The ravager works for me. Check on their eyes.
The body feels very static as I couldn't replicates what fresh did on the vanilla ravager. 
I'm not happy with it, but this is the best I got it working. 
I also remember this mod's mobs acting weird when they are idle and check them in creative. Like they walk half the normal speed 🤷‍♂️
