### ISSUE TITLE
Broken Guard Villagers

### ISSUE THREAD

**Issue by Fyoncle** [SebSemos/F.M.R.P-Freshly-Modded-#4]
https://github.com/SebSemos/F.M.R.P-Freshly-Modded-/issues/3
That issue related to issue 3.

When this will be fixed and be working with EMF 2.2??
I use 1.20.1 Fabric

**Comment by SebSemos** [comment]
I'll try to upload the texture fix this weekend, but EMF 2.2 still broke their attack animations, Traben is investigating. You'll have to use EMF 2.0 for now

**Comment by Fyoncle** [comment]
> I'll try to upload the texture fix this weekend, but EMF 2.2 still broke their attack animations, Traben is investigating. You'll have to use EMF 2.0 for now

EMF Update released, any news?

**Comment by SebSemos** [comment]
Fixed With 2.2.2 of EMF

**Comment by SebSemos** [comment]
Pack also updated :)

**Comment by Fyoncle** [comment]
> Pack also updated :)

Where for modrinth ;(
