### ISSUE TITLE
Iceologer (Friends and Foes) eyes are white

### ISSUE THREAD

**Issue by Acidity01** [SebSemos/F.M.R.P-Freshly-Modded-#9]
Iceologer's eyes are white with no red eyes or brows. ver. 1.21.1

![2024-10-23_10 00 23](https://github.com/user-attachments/assets/ea02a3f6-994e-4906-acfc-e1d200ee038d)

**Comment by Acidity01** [comment]
EMF and ETF versions:

![image](https://github.com/user-attachments/assets/e5d3262a-2760-4c2a-980c-086dc4e54c1b)

**Comment by Acidity01** [comment]
Fixed:
![iceologer](https://github.com/user-attachments/assets/25f51522-ddc1-40a2-b961-c61541210443)

**Comment by SebSemos** [comment]
Oh, nice, i'll update the pack asap :)

**Comment by SebSemos** [comment]
I wonder if you have not another pack. Just checked, my model match my textures. 
I also notice on you screenshot that there is no hood. 
I remember an old version of mine having this issue, but way prior 1.21... so idk 
A new update of freshly modded will be up relatively soon, let me know if you still have this issue.

**Comment by SebSemos** [comment]
Ok, just found out friend and foes in fact use the evoker model on latestupdates. It's been reported and hopefully fix :) 
You can use an older version for now. But idk when this bug has been introduced
